"""add llm metrics to tasks

Revision ID: 0a93edfffc06
Revises: 
Create Date: 2026-08-04 15:09:38.020759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a93edfffc06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('model_name', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('llm_duration_ms', sa.Float(), nullable=True))
    op.add_column('tasks', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('reasoning_tokens', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('cached_tokens', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'total_tokens')
    op.drop_column('tasks', 'cached_tokens')
    op.drop_column('tasks', 'reasoning_tokens')
    op.drop_column('tasks', 'output_tokens')
    op.drop_column('tasks', 'input_tokens')
    op.drop_column('tasks', 'llm_duration_ms')
    op.drop_column('tasks', 'model_name')
    # ### end Alembic commands ###
