"""add requested model to tasks

Revision ID: 430dd182dc42
Revises: 0a93edfffc06
Create Date: 2026-08-05 12:26:40.549355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '430dd182dc42'
down_revision: Union[str, Sequence[str], None] = '0a93edfffc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('requested_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'requested_model')
    # ### end Alembic commands ###
