"""add comparison records

Revision ID: 43f3dceeee01
Revises: 430dd182dc42
Create Date: 2026-08-14 14:43:22.606612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f3dceeee01'
down_revision: Union[str, Sequence[str], None] = '430dd182dc42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table("tasks") as batch_op:
        batch_op.add_column(
            sa.Column(
                "comparison_id",
                sa.Integer(),
                nullable=True,
            )
        )

        batch_op.create_index(
            "ix_tasks_comparison_id",
            ["comparison_id"],
            unique=False,
        )

        batch_op.create_foreign_key(
            "fk_tasks_comparison_id_comparisons",
            "comparisons",
            ["comparison_id"],
            ["id"],
        )
    


def downgrade() -> None:
    """Downgrade schema."""

    with op.batch_alter_table("tasks") as batch_op:
        batch_op.drop_constraint(
            "fk_tasks_comparison_id_comparisons",
            type_="foreignkey",
        )

        batch_op.drop_index(
            "ix_tasks_comparison_id"
        )

        batch_op.drop_column(
            "comparison_id"
        )

    op.drop_table("comparisons")
